#!/usr/bin/env python

"""
Tools for the prediction of spike trains from calcium traces.
"""

import sys
from argparse import ArgumentParser

def main(argv):
	parser = ArgumentParser(argv[0], description=__doc__)

	subparsers = parser.add_subparsers()
	subparser = subparsers.add_parser('preprocess',
		help='Remove trends and normalize sampling rate in data.')
	subparser.add_argument('--command', default='preprocess')
	subparser = subparsers.add_parser('predict',
		help='Predict firing rates from calcium traces.')
	subparser.add_argument('--command', default='predict')
	subparser = subparsers.add_parser('train',
		help='Train a model with calcium traces and simultaneously recorded spikes.')
	subparser.add_argument('--command', default='train')
	subparser = subparsers.add_parser('evaluate',
		help='Evaluate predictins in terms of correlations or Poisson log-likelihood.')
	subparser.add_argument('--command', default='evaluate')
	subparser = subparsers.add_parser('leave-one-out',
		help='Predict firing rates of each cell by training on all other cells.')
	subparser.add_argument('--command', default='leave-one-out')

	args = parser.parse_args(argv[1:2])

	return __import__('c2s-{0}'.format(args.command)).main([' '.join(argv[:2])] + argv[2:])



if __name__ == '__main__':
	sys.exit(main(sys.argv))
