#!/usr/bin/env python

import sys
from argparse import ArgumentParser

def main(argv):
	parser = ArgumentParser(argv[0], description=__doc__)

	subparsers = parser.add_subparsers()
	subparser = subparsers.add_parser('preprocess',
		help='Remove trends and normalize sampling rate in data.')
	subparser.add_argument('--command', default='preprocess')
	subparser = subparsers.add_parser('predict',
		help='Predict firing rates from calcium traces.')
	subparser.add_argument('--command', default='predict')
	subparser = subparsers.add_parser('train',
		help='Train a model with calcium traces and simultaneously recorded spikes.')
	subparser.add_argument('--command', default='train')

	args = parser.parse_args(argv[1:2])

	return __import__('c2s-{0}'.format(args.command)).main([' '.join(argv[:2])] + argv[2:])



if __name__ == '__main__':
	sys.exit(main(sys.argv))
